version: '3.8'

services:
  app:
    build:
      context: .
      target: builder
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD-SHELL", "node healthcheck.js || curl -f http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      NODE_ENV: production
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M